### ISSUE TITLE
Defense useless

### ISSUE THREAD

**Issue by justschmitti** [Adam13531/BotLand#114]
Defense stucks when reaching the right end of the board. They won't run back and fight the other bots.

**Comment by Adam13531** [comment]
Lots of people have commented on this. I'd intended for this to be a sort of "rite of passage" for Bot Land; the default defense has an exploitable hole in it, so you'd watch a few replays and then try to figure out how to improve it. Some people like that idea, some think it's a bug, and some don't like how the default defenses can all be beaten with the same strategy.

There are two things that I'm going to do about this:
1. I'm going to test out making defenders move randomly at the end of the default script rather than move all the way to the left. This should be present after version 0.2.1 (which should happen in the next couple of days).
2. I will eventually [hopefully] revamp the whole tutorial. My plan is to let users *not* have a defense at first so that they can skip right to attacking. By doing so, maybe I could cut down on the number of "default" defenses.
