### ISSUE TITLE
can't find CPU?

### ISSUE THREAD

**Issue by Lyrcaxis** [Adam13531/BotLand#116]
**Steps to reproduce**
I was perfecting my stealth kill CPU script then I noticed bot can't find the enemy cpu..(??)
tried using the premade script to check and yup..
http://prntscr.com/h755az is the blocky code
```
update = function () {
    closestEnemy = findEntity(ENEMY, CPU, SORT_BY_DISTANCE, SORT_ASCENDING);
    if (exists(closestEnemy)) {
        pursue(closestEnemy);
    }
}; 
```
 is the js code
**Expected outcome**
PursueEnemyCPU();
**Actual outcome**
WaitForDeath();
**Browser information**
{"name":"Chrome","chrome":true,"version":"61.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 73
Player name: Lyrcaxis

----- Well, also noticed a bug with the default AI behaviors.. Give my replay with "chris" a view

**Comment by Adam13531** [comment]
@Lyrcaxis this is not a bug, although it's certainly not clear in the game. Bots only have a vision range of 5 tiles by default, so as far as the bot is concerned, anything outside of that range doesn't exist. I'm thinking of changing this specifically for CPUs since they're kind of a special case, but until then, this video is the best I can leave you with: https://youtu.be/neYbay-ZYjo
