### ISSUE TITLE
Boosting Bug

### ISSUE THREAD

**Issue by tehstun** [Adam13531/BotLand#13]
This can lead to people ruining there score and boosting others

**Steps to reproduce**
Edit inGameState ("isAttacker") while in defence and hit forfeit 
**Expected outcome**
nothing
**Actual outcome**
thinks its forfeiting and tanks your score
**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 21
Player name: digi

**Comment by Adam13531** [comment]
What you're doing is calling the forfeitGame() API when you're not supposed to be. This will forfeit whatever match you were playing as an attacker. You're not supposed to be able to do this while defending, but it's similar to watching a replay while editing your defense: you're not *supposed* to do it, but there's nothing wrong with it, and the UI doesn't have to look right because it's not a supported scenario.
