### ISSUE TITLE
Moving a bot with drag'n'drop doesn't work when you do it quickly

### ISSUE THREAD

**Issue by svenhofstede** [Adam13531/BotLand#14]
**Steps to reproduce**
Place a bot, try to move it by clicking on it and moving it to another square quickly

**Expected outcome**
Move the bot from one square to the other

**Actual outcome**
The move doesn't register. The bot remains where it is. The icon of the bot also doesn't attach together with the mouse cursor.
It works if you click on the bot and hold for a second and THEN drag.

**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 38
Player name: svenhof

**Comment by HiDeoo** [comment]
Related to #9.

**Comment by Adam13531** [comment]
I'm not sure if this is a bug exactly. Issue #9, as @HiDeoo mentioned, is related to this bug, and it's where I commented that I increased the threshold time for dragging a bot from 100ms to 200ms.

There are probably still some quirks with tapping vs. pressing, but I think that a full fix would take much longer as it may involve making changes to HammerJS directly. For now, if there's a persistent problem (e.g. you can *never* drag or *never* tap), then please reopen this bug. Otherwise I don't think there's much I can do here.
