### ISSUE TITLE
Request: Show Cooldown (how long I have to wait til I get the next ranked game)

### ISSUE THREAD

**Issue by renatobacchi** [Adam13531/BotLand#148]
Can we show the cooldown time?
ATM it can happen, that one can only play unranked games after a given time.

**Comment by Adam13531** [comment]
(going to write a clarifying comment here to myself, then I'll respond to you afterward)

Note to self: at the time this issue was filed, we'd in Beta with 75-100 potential defenders. An attacker can only play against each defender in a ranked match once every 24 hours, so what @renatobacchi wants is a way to know when the 24 hours is going to "run out" for a player from a while ago so that you can play another ranked match.

With that out of the way, I have some thoughts here that are leading me to close this issue:

* It's not necessarily just the passage of time that will allow you to play ranked games again; if a new player signs up for Bot Land [and completes the tutorial], they'll be added to the pool of potential defenders, and you'll play a ranked match even before the proposed timer would say that you could play one.
* If I did add a timer and it said "20 hours until the next ranked match", I think that it would turn off certain players who want ratings/rewards. By *not* giving them that information, they may continue to play and generate replays for other players.
* Eventually, this won't be a problem. Either there won't be enough players for you to play ranked matches, in which case I essentially have to consider Bot Land dead and try to move on, or there *will* be enough players such that you could never practically play against all of them in a day.

I recognize that this cooldown time may be helpful just for Beta, but the above reasons still apply even for Beta.
