### ISSUE TITLE
Winning a match as Attacker lowers your ATK ranking

### ISSUE THREAD

**Issue by renatobacchi** [Adam13531/BotLand#154]
**Steps to reproduce**
1. Play ranked match
- Rank difference must be greater than about 500
- There must be other factors because it does not happen all the time.
2. Win

**Expected outcome**
Gain Atk Skill

**Actual outcome**
Loose Atk Skill
see: https://imgur.com/a/EXrxQ

**Browser (and version)**
FF 57

**Operating system (and version)**
Win 10 x64 1709

**Comment by HiDeoo** [comment]
This is currently the expected / accepted behaviour and your rating can go up when losing or go down when winning.

This is due to how the Glicko 2 ranking system used in the game works. To get a more detailed answer and read about plans on how to address this issue, you can check [@Adam13531's answer on this subject](https://github.com/Adam13531/BotLand/wiki/Not-very-frequently-asked-questions#why-did-my-rating-go-up-despite-losing-a-game).

**Comment by Adam13531** [comment]
It took approximately one eternity, but I've finally fixed this bug. Commit hash: 2c5ec089376843194f0190c294489edaf5e87959

Fix will be present after version 0.2.29. Just going to copy/paste my commit message here:

> The solution I decided on is this: if a match would cause your Glicko rating to change in an unexpected way (e.g. you win, but your displayed rating still drops), I instead freeze your displayed rating and adjust your deviation so that the numbers still work out.
