### ISSUE TITLE
After editing defense, battle log's "...ago" label gets reset between battle log tab and news tab

### ISSUE THREAD

**Issue by ericthornton** [Adam13531/BotLand#160]
**Steps to reproduce**

1. Edit defense
2. Save to account server and get back to main play.bot.land screen
3. Highest item in battle log shows that "You updated your defense" and the timer begins counting up
4. Switch to news tab
5. Switch back to battle log
6. Timer has been reset and begins counting up from 0 again

**Expected outcome**
Timer is based on when the defense was last updated

**Actual outcome**
TImer appears to be based on when the battle log screen was last shown

**Browser information**
{"name":"Chrome","chrome":true,"version":"62.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 262
Player name: boatland

**Comment by Adam13531** [comment]
Just wanted to comment here that this is indeed a bug; the cause is time drift between the server and the client, so what's really happening is the server is giving you a time 1-3 minutes in the future, and the client keeps clamping it to "now". After about 3 minutes, it _should_ appear like there's no way to reproduce this bug.

I need to use NTP or something similar to prevent this from happening.

P.S. nice account name. 👍

**Comment by Skedog** [comment]
I can no longer reproduce this problem in Bot Land `version 0.2.52` - feel free to re-open if it happens again.
