### ISSUE TITLE
Clicking logo doesn't close "store"

### ISSUE THREAD

**Issue by Skedog** [Adam13531/BotLand#167]
**Steps to reproduce**
* Login
* Open the "Store"
* Click on the Bot Land logo

**Expected outcome**
* Close the store and go back to the battlelog, just like the settings popup.

**Actual outcome**
* Nothing happens

**Browser information**
{"name":"Chrome","chrome":true,"version":"63.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 2
Player name: skedog

**Comment by Adam13531** [comment]
As it stands now, this is not a bug, but that's because full-screen pop-ups cover the entire rest of the screen with their background (which is clickable; see below). If this is no longer the case in the future, the bug will likely reappear.

![image](https://user-images.githubusercontent.com/7192897/39491528-99838b7a-4d41-11e8-8ffd-3b3f614280e2.png)
