### ISSUE TITLE
[MOBILE] Pressing the back button completely exits bot.land

### ISSUE THREAD

**Issue by Pnoexz** [Adam13531/BotLand#173]
**Steps to reproduce**
* Login
* Go anywhere*
* Press back button

**Expected outcome**
* Go back to anywhere*

**Actual outcome**
* You are sent back to whatever website you visited last (eg, google)

**Browser information**
{"name":"Chrome","chrome":true,"version":"64.0","blink":true,"android":true,"osversion":"7.0","mobile":true,"a":true}

**In-game information**
Player ID: 1090
Player name: Pnoexz

**Comment by Adam13531** [comment]
To be clear: the _browser's_ back button hasn't been set up to do anything Bot-Land-specific yet, so teeeechnically this isn't a bug. I'll leave this open for now though because I think people still consider it to be a bug.

In the meantime, if your browser supports it, you can pin the site to your home screen and access it like you would an app. By doing so, the browser will remove the address bar entirely, so you won't even be able to hit this bug.

**Comment by freaktechnik** [comment]
I've noticed this quite a bit when trying the game on mobile today. It just seems much more natural to go back than to find wherever the back button was placed in the particular screen (which may currently even be off-screen, since not all UIs are optimized for mobile yet).

**Comment by Skedog** [comment]
As of version [0.2.47](https://github.com/Adam13531/BotLand/wiki/What's-new-(changelog)#client-version-0247-august-23rd-2018), browserHistory (back/forward buttons in the browser) have been implemented, which I do believe has fixed this bug. Feel free to re-open if you run into it again.
