### ISSUE TITLE
Stuck after "completing" attack tutorial

### ISSUE THREAD

**Issue by freaktechnik** [Adam13531/BotLand#255]
**Steps to reproduce**
- Complete "Attack Introduction" tutorial
- Press rocket on post-match screen
- Press <- button on pre-attack screen for real player

**Expected outcome**
Tutorial is done and the home screen is normally usable.

**Actual outcome**
The tutorial message to start an attack is still there and you end up in #249

**Browser information**
{"name":"Firefox","firefox":true,"version":"64.0","gecko":true,"linux":true,"a":true}

**In-game information**
Client version: 0.2.48
Player ID: 25
Player name: freaktechnik

**Comment by Adam13531** [comment]
I found a set of repro steps that may or may not be what you did:

1. Have a blueprint already that can win against the tutorial enemies in one phase.
2. Start the "Attack Introduction" tutorial.
3. When it tells you to tap an enemy bot, ignore that completely. Place your own bots and start the match.
4. You'll win, so the match results will show.
5. Press the "Rocket" button.
6. Press the "←" button.

Expected: what's actually expected is that you can't even perform step 3; that's what derails the tutorial.
Actual: you're still in the tutorial but on the News screen.

**Comment by Adam13531** [comment]
Fixed by preventing the player from commencing matches when unexpected. Note that you can still place bots, so I think you still would have been confused about what to do in the tutorial. Eventually, I hope I can get the user out of what may *seem* like an infinite loop by adding a "skip" button to the "The tutorial has prevented that action" dialog.

Commit hash: f4bd88976a7137089109d0572ff6cdd8c28de510
