### ISSUE TITLE
Tutorial says "you have unsaved changes"

### ISSUE THREAD

**Issue by Skedog** [Adam13531/BotLand#269]
**Steps to reproduce**
Finish the "create a blueprint" tutorial
Click "teach me" 
![](https://i.imgur.com/gjaB2Pr.png)

**Expected outcome**
It starts the next tutorial

**Actual outcome**
It pops up "you have unsaved changes"
![](https://i.imgur.com/YwntDUb.png)

**Comment by Skedog** [comment]
As an edit/update - another problem that came from this was if you click "stay here" - this keeps you in the "test" match, which you can break the future tutorials/etc by doing this.

I guess the options would be:
- Remove the "stay here" button on the unsaved changes dialog here
- If they click "teach me" - just auto-save their changes and start the next tutorial
- Cry?

**Comment by Adam13531** [comment]
Fixed after version 0.2.51. Commit hash: 021078550ec08212bb8b8bf3643ae6599d90b499

The bug was that the dialog was showing in the first place, but the reason that the dialog was popping up was to address a usability concern, which is that the Place Bots tutorial doesn't put you onto the "/game" page if you're already in an AI match. I'll fix that part of the issue later.
