### ISSUE TITLE
Detect changes in edited defense properly

### ISSUE THREAD

**Issue by Adam13531** [Adam13531/BotLand#272]
This is a bug that rhymu8354 came across during his first run through the game. It's particularly tricky...

**Steps to reproduce**
1. Edit defense
2. Create blueprint
3. Hit Create button
4. Test defense
5. Enter first tutorial
6. Skip tutorial
7. Click "attack"

**Expected outcome**
At step 5, you should be asked if you want to save changes to your defense.

**Actual outcome**
You get an error in the console saying "Bug found: trying to call cloneWorkbench when there are blueprint or script modifications. Please report this to Adam.".

**Comment by Skedog** [comment]
You can also repro essentially this same problem by:

- editing your defense
- editing a script
- testing your defense (full test mode)
- finishing the test and clicking the "home" icon ![](https://i.gyazo.com/a2897e0198a087c9db6bc2da3d2fdfdf.png)
- click edit defense and you will get:
![](https://i.gyazo.com/3aca54a4186f044775688115742a2ea3.png)

- click attack and you get:
![](https://i.gyazo.com/897e7c143860a092b98d9c9f18d7bc21.png)

And a refresh will fix the problem. This is due to you having pending changes in your defense that it doesn't prompt you to save before exiting the edit defense page, the same as above with tutorials.

**Comment by Adam13531** [comment]
This will be fixed in the version after 0.2.89.
