### ISSUE TITLE
Mouse cursor 

### ISSUE THREAD

**Issue by ghost** [Adam13531/BotLand#39]
**Steps to reproduce**
I clicked on the "Toggle FPS view" and then F5'd.

**Expected outcome**
I shouldve have a normal mouse cursor I guess.

**Actual outcome**
I had this cursor http://imgur.com/a/oatE7 besides when on links.

**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 110
Player name: AdamBot

**Comment by HiDeoo** [comment]
Can you re-host your image on another service like Imgur?

> https://goo.gl/7iN64R – this goo.gl shortlink has been disabled. It was found to be violating our Terms of Service. Click here and here for more information about our terms and policies respectively.

**Comment by wHisxaa** [comment]
Oh sure, just noticed

**Comment by wHisxaa** [comment]
@HiDeoo Edited, should work now.

**Comment by DennisRas** [comment]
**Found another way to reproduce**
- Edit defense
- Select/highlight one of your bots in the left panel
- Click cancel

The cursor is now still set to 'move' on <html> until you refresh the page.

**Suggestion**
- Deselect/Unhighlight your bot when cancelling/upgrading/saving (not when testing, because you might want to move bots around quickly between tests)

**Comment by HiDeoo** [comment]
This seems to no longer be an issue as I can't repro, feel free to re-open if that's not the case for you.
