### ISSUE TITLE
Bots get moved and chips get removed when upgrading your computer level

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#46]
**Steps to reproduce**
- Have enough exp to upgrade
- Click "Edit Defense"
- Have bots and chips saved already
- Click upgrade

**Expected outcome**
- Bots and chips stay where they are relative to the CPU location when the arena height expands

**Actual outcome**
- Bots are moved upwards if the arena height expands up & down
- Chips are removed as chip slots are moved and/or spawned

Before: 
![](http://i.imgur.com/rPAuHsu.png)

After:
![](http://i.imgur.com/YFX8qJX.png)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"56.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 3852
Player name: Liquidor2

**Comment by Adam13531** [comment]
This is intentional because the size of the Arena changes. The thinking is:

- With bots, we try to keep them in the Arena if possible so that you can relocate them.
- With chips, if the sockets move, then we can't be sure that you'll want the same chips in the Arena, so we force you to place them again in those cases.

I thought about trying to keep your chips and just putting them in different sockets, but I don't think it's a high enough priority for me to change the design right now.
