### ISSUE TITLE
AI players don't attack when testing defense

### ISSUE THREAD

**Issue by mlindgren** [Adam13531/BotLand#56]
**Steps to reproduce**
Edit defense -> Test

**Expected outcome**
AI players attack my CPU

**Actual outcome**
AI just sits at the edge of the arena doing nothing

**Bowser information**
{"name":"Chrome","chrome":true,"version":"56.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 147
Player name: Dag

**Comment by Adam13531** [comment]
This has been fixed and will be in version 0.1.16+.

Technical details: the bug was that when you had a chip, you couldn't test your defense. This was because chips were incorrectly given a CodeComponent, which caused the CodeExecutionSystem to try to find a nonexistent HardwareComponent. Chips can't have hardware for now, so that crashes Test Mode.
