### ISSUE TITLE
EULA allows using people's name & face without their permission for advertising even if they didn't actually upload it into bot.land

### ISSUE THREAD

**Issue by JonasT** [Adam13531/BotLand#89]
EULA allows using people's name & face without their permission for advertising even if they didn't actually upload any of those things as user content into bot land (but e.g. the provider / you happen to find out about it through other ways). This seems like quite an overreach and I suggest it should be changed.

The relevant section is:

> You further hereby grant to XTONOMOUS the unconditional, irrevocable right to use and exploit **your name, likeness and any other information** or material included in any User Content **and in connection with any User Content**, without any obligation to you.

(emphasis by me)

PS: I'm not a lawyer, but I sometimes read terms of use.

**Comment by Adam13531** [comment]
@JonasT first of all, thank you for filing these issues (#89, #90, and #91). Second, sorry for taking so long to get to this.

I have several thoughts that I'd like to include here since they apply to all three issues. I think there's always a risk of sounding dismissive when closing issues without "fixing" them, so I wanted to be as transparent as I could be.

The EULA and TOS were written by my lawyer quite some time ago in preparation for the Alpha release of Bot Land. I'm *not* a lawyer though, so I don't know why certain clauses were included in them. Because of that, I don't fully understand the ramifications of removing or altering them. For example, suppose I wanted to help subsidize the game using ads, and the ad library that I use is somehow not compatible with my EULA after changing a clause. I wouldn't want to be in deeper legal waters as a result of my inexpert changes. Also, perhaps that example is contrived and has a simple answer, but my point is that without knowing the legal purpose of each clause, I can't make those decisions on my own.

With that said, I *could* re-hire my lawyer to help me update the terms, but I imagine that would be expensive and take at least a few hours of back-and-forth. I think my time and money is better spent on developing Bot Land. My view on the EULA/TOS is similar to stance on localization: it's really important, but only if the game is actually popular. If 10 people end up playing Bot Land, then there won't *be* a game since I won't be able to continue development, so this and every other issue on this GitHub will dissolve.

On the other hand, if there are tons of people playing the game, then hopefully I'll have the resources to revisit these issues in the future. The nice thing about these documents is that they aren't set in stone. I can alert people that the terms of service have changed and that they'll need to re-accept them.

Finally, and I realize this carries no weight, but I don't plan on doing anything evil. I recognize that "evil" is in the eye of the beholder and that it's easy to *say* you won't be evil, but my priorities have always been the game first and the business second.

I hope that sheds some light on my decision to close these issues.
